features:
  - institutional
  - institutional+click
  - institutional+click+survey

labels:
  - cur_course_over_median
  - next_year_over_median

models:
  logistic_regression:
    'penalty' : ['l1', 'l2']
  svm:
    'kernel': ['rbf']
    'C': [0.1, 1, 10, 100, 1000]

metrics:
  - acc
  - fpr
  - fnr

ref_groups:
  ethnicity: 'White, non-Hispanic'
  gender: 'Male'

random_seed: 1
max_var_miss: 0.25

best_params_file_path: '/Users/user/hyperparameters.pickle'